version: '3.3'

services:
  
  nerd-dinner-db:
    build:
      context: ../ch06-nerd-dinner-db
      dockerfile: ./Dockerfile

  nerd-dinner-save-handler:
    build:
      context: ../../ch05
      dockerfile: ./ch05-nerd-dinner-save-handler/Dockerfile

  nerd-dinner-index-handler:
    build:
      context: ../../ch05
      dockerfile: ./ch05-nerd-dinner-index-handler/Dockerfile

  nerd-dinner-homepage:
    build:
      context: ../../ch03/ch03-nerd-dinner-homepage
      dockerfile: ./Dockerfile

  nerd-dinner-web:
    build:
      context: ../../ch05/ch05-nerd-dinner-web
      dockerfile: ./Dockerfile